apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: log-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-sample
  template:
    metadata:
      annotations:
        "klc.klog.vibly.vip/logs-config.1.log-sample": '{"format":"json","type":"file","path":"/app/logs/main.log","name":"app.log"}'
        "klc.klog.vibly.vip/logs-config.2": '{"format":"containerd","type":"stdout","path":"stdout","name":"app.stdout"}'
      labels:
        app: log-sample
    spec:
      containers:
        - name: log-sample
          image: litecy/klog-central-sample:v0.0.1
          command: [ "/bin/sample" ]
          args: [ "--log=/app/logs/main.log" ]
          env:
            - name: DEVOPS.LOGPILOT.IO-LOGS_CONFIG.0
              value: '{"format":"containerd","type":"file","path":"stdout","name":"app.stdout"}'
            - name: DEVOPS.LOGPILOT.IO-LOGS_CONFIG.1
              value: '{"format":"json","type":"file","path":"/app/logs/*.log","name":"app.log"}'
          volumeMounts:
            - name: log-dir
              mountPath: /app/logs
      volumes:
        - name: log-dir
          emptyDir: {}
